const spritePath = (path) => `${import.meta.env.BASE_URL}${path}`;

export const BATTLE_PHASE = {
  idle: "idle",
  selecting: "selecting",
  release: "release",
  result: "result",
  enemyTurn: "enemyTurn",
  overdrive: "overdrive",
};

export const SPRITES = {
  rent_idle: {
    id: "rent_idle",
    src: spritePath("assets/characters/rent/rent_idle_64x64_4f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 4,
    fps: 6,
    loop: true,
    anchor: "bottom-center",
    usage: "battle_idle",
  },
  rent_chain_select: {
    id: "rent_chain_select",
    src: spritePath("assets/characters/rent/rent_chain_select_64x64_4f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 4,
    fps: 8,
    loop: true,
    anchor: "bottom-center",
    usage: "battle_selecting",
  },
  rent_cast: {
    id: "rent_cast",
    src: spritePath("assets/characters/rent/rent_cast_64x64_6f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 6,
    fps: 12,
    loop: false,
    anchor: "bottom-center",
    usage: "battle_release",
  },
  rent_overdrive: {
    id: "rent_overdrive",
    src: spritePath("assets/characters/rent/rent_overdrive_64x64_6f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 6,
    fps: 10,
    loop: true,
    anchor: "bottom-center",
    usage: "battle_overdrive",
  },
  rent_hit: {
    id: "rent_hit",
    src: spritePath("assets/characters/rent/rent_hit_64x64_3f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 3,
    fps: 10,
    loop: false,
    anchor: "bottom-center",
    usage: "battle_player_hit",
  },
  lunon_idle_fly: {
    id: "lunon_idle_fly",
    src: spritePath("assets/characters/lunon/lunon_idle_fly_64x64_6f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 6,
    fps: 8,
    loop: true,
    anchor: "center",
    usage: "support_idle",
  },
  lunon_chain_hype: {
    id: "lunon_chain_hype",
    src: spritePath("assets/characters/lunon/lunon_chain_hype_64x64_6f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 6,
    fps: 12,
    loop: true,
    anchor: "center",
    usage: "support_selecting",
  },
  paladin_idle: {
    id: "paladin_idle",
    src: spritePath("assets/characters/paladin/paladin_idle_64x64_4f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 4,
    fps: 6,
    loop: true,
    anchor: "bottom-center",
    usage: "enemy_idle",
  },
  paladin_hit: {
    id: "paladin_hit",
    src: spritePath("assets/characters/paladin/paladin_hit_64x64_3f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 3,
    fps: 12,
    loop: false,
    anchor: "bottom-center",
    usage: "enemy_hit",
  },
  paladin_defeat: {
    id: "paladin_defeat",
    src: spritePath("assets/characters/paladin/paladin_defeat_64x64_5f.png"),
    frameWidth: 64,
    frameHeight: 64,
    frameCount: 5,
    fps: 10,
    loop: false,
    anchor: "bottom-center",
    usage: "enemy_defeat",
  },
};

export const pieceSpriteIds = {
  red: "piece_red",
  blue: "piece_blue",
  green: "piece_green",
  yellow: "piece_yellow",
  purple: "piece_purple",
};
